// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('bookstore', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('bookstore', async function() {
    // Test name: bookstore
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("https://brainbites.netlify.app/")
    // 2 | setWindowSize | 1366x727 |  | 
    await driver.manage().window().setRect({ width: 1366, height: 727 })
    // 3 | click | css=.log-in |  | 
    await driver.findElement(By.css(".log-in")).click()
    // 4 | mouseOver | css=.log-in |  | 
    {
      const element = await driver.findElement(By.css(".log-in"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 5 | mouseOut | css=.log-in |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 6 | click | id=username |  | 
    await driver.findElement(By.id("username")).click()
    // 7 | type | id=username | omar | 
    await driver.findElement(By.id("username")).sendKeys("omar")
    // 8 | click | id=password |  | 
    await driver.findElement(By.id("password")).click()
    // 9 | type | id=password | 1234 | 
    await driver.findElement(By.id("password")).sendKeys("1234")
    // 10 | click | css=input:nth-child(1) |  | 
    await driver.findElement(By.css("input:nth-child(1)")).click()
    // 11 | click | css=button:nth-child(4) |  | 
    await driver.findElement(By.css("button:nth-child(4)")).click()
    // 12 | click | css=.bookStore |  | 
    await driver.findElement(By.css(".bookStore")).click()
    // 13 | click | css=.book-box:nth-child(1) > .addToCartBtn |  | 
    await driver.findElement(By.css(".book-box:nth-child(1) > .addToCartBtn")).click()
    // 14 | mouseOver | css=.book-box:nth-child(1) > .addToCartBtn |  | 
    {
      const element = await driver.findElement(By.css(".book-box:nth-child(1) > .addToCartBtn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 15 | mouseOut | css=.added |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 16 | click | css=button:nth-child(2) |  | 
    await driver.findElement(By.css("button:nth-child(2)")).click()
    // 17 | click | css=.book-box:nth-child(2) > .addToCartBtn |  | 
    await driver.findElement(By.css(".book-box:nth-child(2) > .addToCartBtn")).click()
    // 18 | mouseOver | css=.book-box:nth-child(2) > .addToCartBtn |  | 
    {
      const element = await driver.findElement(By.css(".book-box:nth-child(2) > .addToCartBtn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 19 | mouseOut | css=.book-box:nth-child(2) > .addToCartBtn |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 20 | click | css=button:nth-child(2) |  | 
    await driver.findElement(By.css("button:nth-child(2)")).click()
    // 21 | click | css=.book-box:nth-child(3) > .addToCartBtn |  | 
    await driver.findElement(By.css(".book-box:nth-child(3) > .addToCartBtn")).click()
    // 22 | mouseOver | css=.book-box:nth-child(3) > .addToCartBtn |  | 
    {
      const element = await driver.findElement(By.css(".book-box:nth-child(3) > .addToCartBtn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 23 | mouseOut | css=.book-box:nth-child(3) > .addToCartBtn |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 24 | click | css=button:nth-child(2) |  | 
    await driver.findElement(By.css("button:nth-child(2)")).click()
    // 25 | click | css=.book-box:nth-child(4) > .addToCartBtn |  | 
    await driver.findElement(By.css(".book-box:nth-child(4) > .addToCartBtn")).click()
    // 26 | mouseOver | css=.book-box:nth-child(4) > .addToCartBtn |  | 
    {
      const element = await driver.findElement(By.css(".book-box:nth-child(4) > .addToCartBtn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 27 | mouseOut | css=.book-box:nth-child(4) > .addToCartBtn |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 28 | click | css=button:nth-child(2) |  | 
    await driver.findElement(By.css("button:nth-child(2)")).click()
    // 29 | click | css=.book-box:nth-child(5) > .addToCartBtn |  | 
    await driver.findElement(By.css(".book-box:nth-child(5) > .addToCartBtn")).click()
    // 30 | click | css=button:nth-child(2) |  | 
    await driver.findElement(By.css("button:nth-child(2)")).click()
    // 31 | click | css=.book-box:nth-child(6) > .addToCartBtn |  | 
    await driver.findElement(By.css(".book-box:nth-child(6) > .addToCartBtn")).click()
    // 32 | mouseOver | css=.book-box:nth-child(6) > .addToCartBtn |  | 
    {
      const element = await driver.findElement(By.css(".book-box:nth-child(6) > .addToCartBtn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 33 | mouseOut | css=.book-box:nth-child(6) > .addToCartBtn |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 34 | click | css=button:nth-child(2) |  | 
    await driver.findElement(By.css("button:nth-child(2)")).click()
    // 35 | click | css=.cartLogo |  | 
    await driver.findElement(By.css(".cartLogo")).click()
    // 36 | click | css=li:nth-child(1) > .remove |  | 
    await driver.findElement(By.css("li:nth-child(1) > .remove")).click()
    // 37 | click | css=li:nth-child(1) > .remove |  | 
    await driver.findElement(By.css("li:nth-child(1) > .remove")).click()
    // 38 | click | css=li:nth-child(1) > .remove |  | 
    await driver.findElement(By.css("li:nth-child(1) > .remove")).click()
    // 39 | click | css=li:nth-child(1) > .remove |  | 
    await driver.findElement(By.css("li:nth-child(1) > .remove")).click()
    // 40 | click | css=li:nth-child(1) > .remove |  | 
    await driver.findElement(By.css("li:nth-child(1) > .remove")).click()
    // 41 | click | css=.PurchaseBtn |  | 
    await driver.findElement(By.css(".PurchaseBtn")).click()
    // 42 | click | css=label:nth-child(5) > input |  | 
    await driver.findElement(By.css("label:nth-child(5) > input")).click()
    // 43 | click | css=.cardName > input |  | 
    await driver.findElement(By.css(".cardName > input")).click()
    // 44 | type | css=.cardName > input | omar sanchez | 
    await driver.findElement(By.css(".cardName > input")).sendKeys("omar sanchez")
    // 45 | click | css=.CardNumber > input |  | 
    await driver.findElement(By.css(".CardNumber > input")).click()
    // 46 | type | css=.CardNumber > input | 1234 1234 1234 1234 | 
    await driver.findElement(By.css(".CardNumber > input")).sendKeys("1234 1234 1234 1234")
    // 47 | click | css=.SecurityCode |  | 
    await driver.findElement(By.css(".SecurityCode")).click()
    // 48 | click | css=.ExpirationDate > input |  | 
    await driver.findElement(By.css(".ExpirationDate > input")).click()
    // 49 | type | css=.ExpirationDate > input | 12/23 | 
    await driver.findElement(By.css(".ExpirationDate > input")).sendKeys("12/23")
    // 50 | click | css=.SecurityCode > input |  | 
    await driver.findElement(By.css(".SecurityCode > input")).click()
    // 51 | type | css=.SecurityCode > input | 123 | 
    await driver.findElement(By.css(".SecurityCode > input")).sendKeys("123")
    // 52 | click | css=.streetAdress > input |  | 
    await driver.findElement(By.css(".streetAdress > input")).click()
    // 53 | type | css=.streetAdress > input | 2100 s | 
    await driver.findElement(By.css(".streetAdress > input")).sendKeys("2100 s")
    // 54 | type | css=.city > input | salt lake | 
    await driver.findElement(By.css(".city > input")).sendKeys("salt lake")
    // 55 | type | css=.state > input | Guanajuato | 
    await driver.findElement(By.css(".state > input")).sendKeys("Guanajuato")
    // 56 | type | css=.PostalCode > input | 38500 | 
    await driver.findElement(By.css(".PostalCode > input")).sendKeys("38500")
    // 57 | type | css=.PhoneNumber > input | (801)-974-3235 | 
    await driver.findElement(By.css(".PhoneNumber > input")).sendKeys("(801)-974-3235")
    // 58 | click | css=.state > input |  | 
    await driver.findElement(By.css(".state > input")).click()
    // 59 | type | css=.state > input | ng | 
    await driver.findElement(By.css(".state > input")).sendKeys("ng")
    // 60 | click | css=span:nth-child(1) |  | 
    await driver.findElement(By.css("span:nth-child(1)")).click()
  })
})
